---
name: "Setup Shakespeare"
author: Yevhen Fabizhevskyi
description: |
  This GitHub action installs one of the Shakespeare programming language
  interpreters called shakespearelang.
branding:
  icon: italic
  color: yellow
inputs:
  version:
    description: "Shakespearelang library version."
    required: false
    default: "0.3.1"
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      run: |
        SHAKESPEARE_INSTALLED=$(if command -v shakespeare >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "SHAKESPEARE_INSTALLED=$SHAKESPEARE_INSTALLED" >> $GITHUB_OUTPUT
      shell: sh
    - name: Install tools
      if: ${{ steps.info.outputs.SHAKESPEARE_INSTALLED == 'false' }}
      env:
        SETUPTOOLS_VERSION: "69.5.1"
      run: pip install setuptools==$SETUPTOOLS_VERSION
      shell: sh
    - name: Install Shakespeare
      if: ${{ steps.info.outputs.SHAKESPEARE_INSTALLED == 'false' }}
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: pip install shakespearelang==${INPUT_VERSION}
      shell: sh
