---
name: 'Setup Shakespeare'
author: Yevhen Fabizhevskyi
description: 'This GitHub action installs one of the Shakespeare Programming Language interpreters called shakespearelang.'
branding:
  icon: italic
  color: yellow
inputs:
  version:
    description: 'Shakespearelang library version.'
    required: false
    default: null
runs:
  using: 'node16'
  main: 'dist/index.js'
