---
name: 'Setup Shakespeare'
author: Yevhen Fabizhevskyi
description: 'This GitHub action installs one of the Shakespeare Programming Language interpreters called shakespearelang.'
branding:
  icon: italic
  color: yellow
inputs:
  version:
    description: 'Shakespearelang library version.'
    required: false
    default: '0.3.1'
runs:
  using: 'composite'
  steps:
    - name: Install tools
      env:
        SETUPTOOLS_VERSION: 58.1.0
      run: pip install setuptools==$SETUPTOOLS_VERSION
      shell: bash
    - name: Install Shakespeare
      run: pip install shakespearelang==${{ inputs.version }}
      shell: bash
