---
name: "Setup Shakespeare"
author: Yevhen Fabizhevskyi
description: |
  This GitHub action installs one of the Shakespeare programming language
  interpreters called shakespearelang.
branding:
  icon: italic
  color: yellow
inputs:
  version:
    description: shakespearelang library version. Defaults to the latest version.
    required: false
    default: "latest"
  force:
    description: |
      If "false" skips installation if shakespeare is already installed. If "true"
      installs shakespeare in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether shakespeare was installed or not.
    value: "${{ steps.install-shakespeare.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install dependencies
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      env:
        SETUPTOOLS_VERSION: "75.6.0"
      run: |
        pip install setuptools==$SETUPTOOLS_VERSION ${{ runner.os == 'Windows' && 'pyreadline3' || ''}}
      shell: sh

    - name: Get latest release
      if: ${{ steps.info.outputs.bin-installed == 'false' && inputs.version == 'latest' }}
      id: latest-release
      env:
        TARGET_PIP_PACKAGE: "shakespearelang"
      run: ./get-latest-release.sh "${TARGET_PIP_PACKAGE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install Shakespeare
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-shakespeare
      env:
        VERSION: "${{ inputs.version == 'latest' && steps.latest-release.outputs.version || inputs.version }}"
      run: pip install shakespearelang==${VERSION}
      shell: sh
